
package com.conducivetech.cache.flighthistory.api_internal.v2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "APIException", targetNamespace = "http://v2.api_internal.flighthistory.cache.conducivetech.com/")
public class APIException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private APIException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public APIException_Exception(String message, APIException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public APIException_Exception(String message, APIException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.conducivetech.cache.flighthistory.api_internal.v2.APIException
     */
    public APIException getFaultInfo() {
        return faultInfo;
    }

}
