
package com.conducivetech.cache.flighthistory.api_internal.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RouteSoapApiService", targetNamespace = "http://v2.api_internal.flighthistory.cache.conducivetech.com/", wsdlLocation = "https://api.flightstats.com/flex/flightstatus/docs/v2/lts/soap/routeService.wsdl")
public class RouteSoapApiService
    extends Service
{

    private final static URL ROUTESOAPAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException ROUTESOAPAPISERVICE_EXCEPTION;
    private final static QName ROUTESOAPAPISERVICE_QNAME = new QName("http://v2.api_internal.flighthistory.cache.conducivetech.com/", "RouteSoapApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.flightstats.com/flex/flightstatus/docs/v2/lts/soap/routeService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROUTESOAPAPISERVICE_WSDL_LOCATION = url;
        ROUTESOAPAPISERVICE_EXCEPTION = e;
    }

    public RouteSoapApiService() {
        super(__getWsdlLocation(), ROUTESOAPAPISERVICE_QNAME);
    }

    public RouteSoapApiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROUTESOAPAPISERVICE_QNAME, features);
    }

    public RouteSoapApiService(URL wsdlLocation) {
        super(wsdlLocation, ROUTESOAPAPISERVICE_QNAME);
    }

    public RouteSoapApiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROUTESOAPAPISERVICE_QNAME, features);
    }

    public RouteSoapApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RouteSoapApiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RouteService
     */
    @WebEndpoint(name = "routeServicePort")
    public RouteService getRouteServicePort() {
        return super.getPort(new QName("http://v2.api_internal.flighthistory.cache.conducivetech.com/", "routeServicePort"), RouteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RouteService
     */
    @WebEndpoint(name = "routeServicePort")
    public RouteService getRouteServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://v2.api_internal.flighthistory.cache.conducivetech.com/", "routeServicePort"), RouteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROUTESOAPAPISERVICE_EXCEPTION!= null) {
            throw ROUTESOAPAPISERVICE_EXCEPTION;
        }
        return ROUTESOAPAPISERVICE_WSDL_LOCATION;
    }

}
